### ISSUE TITLE
configure: error: *** -lrcsc not found! ***

### ISSUE THREAD

**Issue by hzonuz** [helios-base/soccerwindow2#37]
Hi I want to install soccerwindow on my ubuntu but when I want to configure with ``` ./configure --with-librcsc=/usr/local/lib```, it throws this error ```configure: error:  -lrcsc not found! ``` what should I do?
I'm sure that my librcsc installed in ```/usr/local/lib``` path.

**Comment by hidehisaakiyama** [comment]
Make sure /usr/local/lib/librcsc.so exists.
If not, librcsc you installed may be too old.

**Comment by hidehisaakiyama** [comment]
If additional information, please reopen this issue.

**Comment by hidehisaakiyama** [comment]
If additional information, please reopen this issue.
